added model book, and repo with service.
opopovych/onlineBookStore pull request #1
Opened 2023-10-18 21:45 UTC by opopovych

2023-10-19 10:45 UTC, Rommelua requested changes

2023-10-19 10:45 UTC, Rommelua commented on src/main/java/mate/academy/model/Book.java
> +    @Nonnull
@Column(nullable = false)

2023-10-20 10:48 UTC, kerrrusha approved these changes
see comments

2023-10-20 10:48 UTC, kerrrusha commented on mvnw
> +#!/bin/sh
in future, don't include this file to the git

2023-10-20 10:48 UTC, kerrrusha commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
dont include this too

2023-10-20 10:48 UTC, kerrrusha commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.5/apache-maven-3.9.5-bin.zip
don't include this file too, as like as maven-wrapper.jar

2023-10-20 10:48 UTC, kerrrusha commented on src/main/java/mate/academy/OnlineBookStoreApplication.java
> +
redundant blank line

2023-10-20 10:48 UTC, kerrrusha commented on src/main/java/mate/academy/OnlineBookStoreApplication.java
> +
redundant blank line

2023-10-26 12:20 UTC, merged