Shoppingcart practies
opopovych/onlineBookStore pull request #14
Opened 2024-03-11 18:33 UTC by opopovych

2024-03-12 09:32 UTC, Rommelua requested changes

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/dto/cartitem/AddItemToCartRequestDto.java
> +        Long bookId,
NotNull

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/dto/cartitem/AddItemToCartRequestDto.java
> +        int quantity
NotNull

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/model/ShoppingCart.java
> +@Data
do not use `@Data` with Entity classes

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/model/CartItem.java
> +public class CartItem {
![image](https://github.com/opopovych/onlineBookStore/assets/20326858/ef59717f-4124-453a-a3ee-9d40fc80ab7c)

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/repository/cartitem/CartItemRepository.java
> +    void deleteByShoppingCartId(Long cartId);
![image](https://github.com/opopovych/onlineBookStore/assets/20326858/6360200d-9ad1-4e00-83ec-e6e7f4b12914)

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +    ShoppingCart createShoppingCart(User user);
do we use it?

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +    ShoppingCartDto addBooksToCartByUserId(Long userId, AddItemToCartRequestDto requestDto);
```suggestion
    ShoppingCartDto addBookToCartByUserId(Long userId, AddItemToCartRequestDto requestDto);
```

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +    ShoppingCartDto getCartDtoByUserId(Long id);
```suggestion
    ShoppingCartDto getCartByUserId(Long id);
```

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +    ShoppingCart getCartByUserId(Long id);
```suggestion
```

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto addBooksToCartByUserId(Long userId, AddItemToCartRequestDto requestDto) {
Add `@Transactional`

2024-03-12 09:32 UTC, Rommelua commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +        return cartMapper.toDto(getCartFromDb(userId));
```suggestion
        return cartMapper.toDto(cartFromDb);
```

2024-03-12 22:26 UTC, opopovych commented
i can not understand, why all checks was failed. i think, that i did all correctly.

2024-03-13 12:19 UTC, Rommelua requested changes

2024-03-13 12:19 UTC, Rommelua commented on src/main/java/mate/academy/repository/cartitem/CartItemRepository.java
> +    void deleteByShoppingCartId(Long cartId);
not fixed - use soft delete

2024-03-16 12:18 UTC, okuzan requested changes

2024-03-16 12:18 UTC, okuzan commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +@RequestMapping("/api/cart")
extract api to server servlet context-path property

2024-03-16 12:18 UTC, okuzan commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +        return shoppingCartService.getCartByUserId(user.getId());
maybe let's create a private method to get userId from authentication?

2024-03-16 12:18 UTC, okuzan commented on src/main/java/mate/academy/model/CartItem.java
> +@Where(clause = "deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE cart_items SET deleted = TRUE WHERE id = ?")
@SQLRestriction(clause = "deleted = FALSE")
```

2024-03-16 12:18 UTC, okuzan commented on src/main/java/mate/academy/model/ShoppingCart.java
> +
```suggestion
```

2024-03-16 12:18 UTC, okuzan commented on src/main/java/mate/academy/model/CartItem.java
> +
```suggestion
```

2024-03-16 12:18 UTC, okuzan commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +
```suggestion
```

2024-03-16 12:18 UTC, okuzan commented on src/main/resources/db/changelog/changes/10-create-shopping-cart-table.yaml
> +            tableName: shopping_carts
```suggestion
            tableName: shopping_carts

```
add empty line wherever you see this red symbol in your PR

2024-03-16 12:18 UTC, okuzan commented on src/main/resources/db/changelog/changes/10-create-shopping-cart-table.yaml
> +            tableName: shopping_carts
![image](https://github.com/opopovych/onlineBookStore/assets/49767049/4daee2ae-a1cd-4625-a051-38054ac9f0c0)

2024-03-17 12:45 UTC, MentorMA requested changes

2024-03-17 12:45 UTC, MentorMA commented on src/main/java/mate/academy/model/CartItem.java
> +//@Where(clause = "deleted = FALSE")
Commented code

2024-03-17 12:45 UTC, MentorMA commented on src/main/java/mate/academy/repository/cartitem/CartItemRepository.java
> +@Repository
This annotation is not mandatory

2024-03-17 19:41 UTC, merged